version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///cocktails.db
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT}
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-15-preview}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./instance:/app/instance
    networks:
      - cocktail-network

  frontend:
    build:
      context: ./frontend-react/le_mixologue_augmente
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - cocktail-network

networks:
  cocktail-network:
    driver: bridge